#!/bin/bash
python medicalbert/ --experiment_name alsentzer1 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10python medicalbert/ --experiment_name alsentzer5e5 --learning_rate 0.00005 --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --train --eval --classifier bert-general;
python medicalbert/ --experiment_name alsentzer2 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer3 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer4 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer5 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer6 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer7 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer8 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer9 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10
python medicalbert/ --experiment_name alsentzer10 --learning_rate 0.00001 --train --eval --classifier bert-general --tokenizer /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --pretrained_model /home/apatterson/pretrained_bert_tf/biobert_pretrain_output_disch_100000 --epochs 10